CREATE DATABASE ORDER;

CREATE USER 'session'@'XXXXXXXX' IDENTIFIED BY 'HappyHour&';
CREATE USER 'purchase'@'XXXXXXXX' IDENTIFIED BY 'MorningSunshine$';

-- Using VPC IP segment for AWS Lambda access control
GRANT SELECT, INSERT, DELETE, UPDATE, EXECUTE ON ORDER.* TO 'session'@'XXXXXXXXX';
GRANT SELECT, INSERT, DELETE, UPDATE, EXECUTE ON ORDER.* TO 'purchase'@'XXXXXXXXX';

FLUSH PRIVILEGES;