USE ORDER;

CREATE TABLE IF NOT EXISTS SESSION (
   SESSION_UUID        VARCHAR(100) NOT NULL UNIQUE,
   JWT_TOKEN           VARCHAR(100) NOT NULL UNIQUE,
   CREATION_EPOCH_TIME INT NOT NULL,
   IS_IN_QUEUE         BOOLEAN NOT NULL DEFAULT 1,
   PRIMARY KEY ( SESSION_UUID ),
   INDEX ( CREATION_EPOCH_TIME )
);

CREATE TABLE IF NOT EXISTS PURCHASE (
   PURCHASE_UUID          VARCHAR(100) NOT NULL UNIQUE,
   USER_UUID          VARCHAR(100) NOT NULL UNIQUE,
   ITEM_UUID           VARCHAR(100) NOT NULL UNIQUE,
   QUANTITY            INT NOT NULL,
   CREATION_EPOCH_TIME INT NOT NULL,
   PRIMARY KEY ( PURCHASE_UUID ),
   FOREIGN KEY (USER_UUID) REFERENCES USER(USER_UUID),
   FOREIGN KEY (ITEM_UUID) REFERENCES ITEM(ITEM_UUID)

);

CREATE TABLE IF NOT EXISTS USER (
   USER_UUID          VARCHAR(100) NOT NULL UNIQUE,
   FIRST_NAME          VARCHAR(30) NOT NULL UNIQUE,
   LAST_NAME           VARCHAR(100) NOT NULL UNIQUE,
   EMAIL               VARCHAR(50) NOT NULL UNIQUE,
   MOBILE              VARCHAR(20) NOT NULL UNIQUE,
   CREATION_EPOCH_TIME INT NOT NULL,
   PRIMARY KEY ( USER_UUID )
);

CREATE TABLE IF NOT EXISTS ITEM (
   ITEM_UUID          VARCHAR(100) NOT NULL UNIQUE,
   ITEM_NAME          VARCHAR(30) NOT NULL UNIQUE,
   ITEM_DESCRIPTION    VARCHAR(100) NOT NULL UNIQUE,
   PRICE               FLOAT(5,2) NOT NULL UNIQUE,
   CREATION_EPOCH_TIME INT NOT NULL,
   PRIMARY KEY ( ITEM_UUID )
);